INSERT INTO operator (atoc_code, name) VALUES
('LM', 'West Midlands Trains'),
('WR', 'West Coast Railways'),
('ZZ', 'VolkerRail'),
('EU', 'Virtual European Paths'),
('TY', 'Vintage Trains'),
('AW', 'Transport for Wales'),
('TP', 'TransPennine Express'),
('SP', 'Swanage Railway'),
('SN', 'Southern'),
('SE', 'Southeastern'),
('SW', 'South Western Railway'),
('SR', 'ScotRail'),
('ME', 'Merseyrail'),
('LD', 'Lumo'),
('LT', 'LUL District Line - Wimbledon / Richmond / Bakerloo'),
('LO', 'London Overground'),
('GR', 'London North Eastern Railway'),
('LS', 'Locomotive Services'),
('HT', 'Hull Trains'),
('HX', 'Heathrow Express'),
('EM', 'East Midlands Railway'),
('ES', 'Caledonian Sleeper / Eurostar'),
('XR', 'Elizabeth line'),
('XC', 'CrossCountry'),
('CH', 'Chiltern Railways'),
('CC', 'c2c'),
('VT', 'Avanti West Coast'),
('PE', 'GB Railfreight'),
('DH', 'Freightliner Heavy Haul'),
('FL', 'Freightliner Intermodal'),
('FD', 'DB Cargo International'),
('WA', 'DB Cargo Freight'),
('FM', 'DB Cargo Charters'),
('PH', 'Rail Operations Group'),
('PO', 'DC Rail'),
('EX', 'Elizabeth line');