INSERT INTO operator (atoc_code, name) VALUES
('NT', 'Northern Trains'),
('AW', 'Transport for Wales'),
('CC', 'c2c'),
('CS', 'Caledonian Sleeper'),
('CH', 'Chiltern Railways'),
('XC', 'CrossCountry'),
('EM', 'East Midlands Railway'),
('ES', 'Eurostar'),
('HT', 'Hull Trains'),
('GX', 'Gatwick Express'),
('GN', 'Govia Thameslink Railway (Great Northern)'),
('TL', 'Govia Thameslink Railway (Thameslink)'),
('GC', 'Grand Central'),
('GW', 'Great Western Railway'),
('LE', 'Greater Anglia'),
('HC', 'Heathrow Connect'),
('HX', 'Heathrow Express'),
('IL', 'Island Lines'),
('LS', 'Locomotive Services'),
('LM', 'West Midlands Trains'),
('LO', 'London Overground'),
('LT', 'London Underground'),
('ME', 'Merseyrail'),
('TW', 'Nexus (Tyne & Wear Metro)'),
('SR', 'ScotRail'),
('SW', 'South Western Railway'),
('SJ', 'South Yorkshire Supertram'),
('SE', 'Southeastern'),
('SN', 'Southern'),
('SP', 'Swanage Railway'),
('XR', 'Elizabeth line'),
('TP', 'TransPennine Express'),
('VT', 'Avanti West Coast'),
('GR', 'London North Eastern Railway'),
('WR', 'West Coast Railways'),
('TY', 'Vintage Trains'),
('LD', 'Lumo'),
('FS', 'Fishbone Solutions'),
('LF', 'Grand Union Trains'),
('XJ', 'Ffestiniog Railway'),
('MV', 'Varamis Rail');